### ISSUE TITLE
Core: fix session context fails on first session

### ISSUE THREAD

**Issue by bernardosrulzon** [snowplow/snowplow-android-tracker#176]
Guys -

I'm seeing a seemingly legitimate row fail the `client_session` validation because its `previousSessionId` is set to an empty string. That happens because the `sessionIndex` is 1 - it's the user's first session.

Please find attached the JSON that is failing: [session_context.txt](https://github.com/snowplow/snowplow-android-tracker/files/34224/session_context.txt)

What is the intended behaviour of the field `previousSessionId` on the first session? I guess it's supposed to be null. Should we treat that inside our Android app somehow?

**Comment by alexanderdean** [comment]
Thanks for raising! Sounds like a bug, assigned to @jbeemster

**Comment by alexanderdean** [comment]
See https://github.com/snowplow/iglu-central/blob/master/schemas/com.snowplowanalytics.snowplow/client_session/jsonschema/1-0-1#L25

**Comment by bernardosrulzon** [comment]
Great! @jbeemster should [this](https://github.com/snowplow/snowplow-android-tracker/blob/master/snowplow-android-core/src/main/java/com/snowplowanalytics/snowplow/tracker/constants/TrackerConstants.java#L31) be bumped to 1-0-1 too?

**Comment by bernardosrulzon** [comment]
@jbeemster I looked a little bit into this:

1. The problem seems to live [here](https://github.com/snowplow/snowplow-android-tracker/blob/master/snowplow-android-core/src/main/java/com/snowplowanalytics/snowplow/tracker/Session.java#L233-L239) - this method returns the previous session id or an empty string
2. That happens because the previous session id is updated [here](https://github.com/snowplow/snowplow-android-tracker/blob/master/snowplow-android-core/src/main/java/com/snowplowanalytics/snowplow/tracker/Session.java#L169) to the value of the current session id, which is an [empty string](https://github.com/snowplow/snowplow-android-tracker/blob/master/snowplow-android-core/src/main/java/com/snowplowanalytics/snowplow/tracker/Session.java#L49) on the first session.

That's pretty much as far as my Java skills go. I'm updating the session_context schema our our iglu server to remove the uuid validation until the next version comes.

Thanks!

**Comment by jbeemster** [comment]
Hi @bernardosrulzon thanks for raising this.  The current session ID needs to be set to null not an empty string on this line which should solve the problem: 

https://github.com/snowplow/snowplow-android-tracker/blob/master/snowplow-android-core/src/main/java/com/snowplowanalytics/snowplow/tracker/Session.java#L49

**Comment by bernardosrulzon** [comment]
Thanks! @jbeemster should [this](https://github.com/snowplow/snowplow-android-tracker/blob/master/snowplow-android-core/src/main/java/com/snowplowanalytics/snowplow/tracker/constants/TrackerConstants.java#L31) be bumped to 1-0-1 too?

**Comment by jbeemster** [comment]
Hey @bernardosrulzon that will happen in the 0.6.0 release!  We try to keep bug fixes and core changes/updates separated.

**Comment by alexanderdean** [comment]
See: https://github.com/snowplow/snowplow-android-tracker/issues/160

**Comment by bernardosrulzon** [comment]
@jbeemster @alexanderdean

This doesn't seem to have solved the problem - i'm still getting tons of validation failures due to `previousSessionId = null`. This seems to be a critical problem to android users. Please let me know if I can help you with debugging.

Should I open a new issue?

**Comment by alexanderdean** [comment]
Hi @bernardosrulzon - can you share the exact error message you are seeing?

The schema in Iglu Central explicitly permits `previousSessionId = null`:

https://github.com/snowplow/iglu-central/blob/master/schemas/com.snowplowanalytics.snowplow/client_session/jsonschema/1-0-0#L27

So something strange is going on...

**Comment by bernardosrulzon** [comment]
@alexanderdean 

Ah, false alarm - sorry about that! Before you fixed this bug, I manually edited the schema to allow only strings. Then we upgraded Snowplow, but I forgot to remove the edited schema. Oops!

Thanks for your help!

**Comment by alexanderdean** [comment]
No worries, glad we got it resolved!

**Comment by bernardosrulzon** [comment]
@alexanderdean actually, we'll need to update the schema because it expects an uuid. please check the error message below:

```json
"errors": [{
	"level": "error",
	"message": "error: input string \"null\" is not a valid UUID\n    level: \"error\"\n    schema: {\"loadingURI\":\"#\",\"pointer\":\"/properties/previousSessionId\"}\n    instance: {\"pointer\":\"/previousSessionId\"}\n    domain: \"validation\"\n    keyword: \"format\"\n    attribute: \"uuid\"\n    value: \"null\"\n"
}]```

does that make sense?

**Comment by alexanderdean** [comment]
Hey @bernardosrulzon - the way JSON Schema works, the UUID format will only apply to the String type. The null type is orthogonal to the UUID format requirement.

Your error message suggests that somehow the string `"null"` rather than the type `null` is making it through - that would be a bug. Adding @jbeemster to verify whether there is a bug in the tracker code here.
